#' MCV Criterion for the Selection of \eqn{\lambda}.
#'
#'
#'\code{multifoldCV} calculates the multi-fold crossvalidation (MCV) criterion
#'for choosing the smoothness parameter in quantile smoothing splines. The MCV
#' criterion was proposed by Reiss et al. in 2012. Reiss et al. and our own
#' simulations demonstrate this is criterion is suitable as a reliable automatic
#'  procedure to choose the optimal smoothing parameter.
#'
#'In general, the optimal degree of smoothness will depend on the quantile of
#'interest. Given a value \eqn{\tau\in [0,1]}, nonparametric quantile regression
#' seeks to estimate the conditional quantile function \eqn{g(x)} minimizing:
#'\deqn{\sum_{i=1}^n \rho_{\tau}[y_i-g(x_i)]+\lambda J(g)}
#'where J(g) is the total variation of g(x).
#'Multifold CV (Reiss, 2012) can greatly reduce the computational burden. Here
#'we divide the \eqn{n} observations into \eqn{V_1,\cdots,V_k} of
#'(approximately) equal size, and define the criterion:
#'\deqn{MCV=\frac{1}{n}\sum_{j=1}^k\sum_{i\in V_j}
#'\rho_{\tau}[y_i-\hat{g}_{\lambda}^{[-V_j]}(x_i)]} where
#'\eqn{\hat{g}_{\lambda}^{[-V_j]}} is the function estimate based on all
#'observations except those in fold \eqn{V_j}. Small values of \eqn{k}
#'produce downward-biased estimates of prediction error, whereas larger values
#'produce more variable results and impose a higher computational burden;
#'\eqn{k=5 or 10} is often recommended as a compromise.
#'
#'@import quantreg
#'@import doParallel
#'@import foreach
#'@import tripack
#'
#'@param cores The number of cores to use for parallel execution. If not
#'  specified, the number of cores is set to the value of
#'  \code{options("cores")}, if specified, or to one-half the number of cores
#'  detected by the \code{\link{parallel}} package.
#'@param sim.data A data frame (or object coercible by
#'  \code{\link{as.data.frame}} to a data frame) for which we are selecting the
#'  smoothing parameter.
#'@param tau A specific quantile to be estimated. Must be a number between 0 and
#'  1.
#'@param lambda The smoothing parameter governing the tradeoff between fidelity
#'  and the penalty component for the triogram term.
#'@param cv.idx The folds (the divided data) randomly generated by
#'\code{\link{foldsGenerator}}.
#'
#'
#'@return The MCV criterion is returned.
#'@examples
#' data(one)
#' folds<-foldsGenerator(sim.data=one,nfolds=10)
#' multifoldCV(cores=3,lambda=2,tau=0.5,sim.data=one,cv.idx=folds)
#'
#' data(two)
#' folds<-foldsGenerator(sim.data=two,nfolds=10)
#' multifoldCV_2dim(cores=3,lambda=2,tau=0.5,sim.data=two,cv.idx=folds)
#'
#'@references Reiss et al. (2012). \eqn{Smoothness Selection for penalized Quantile Regression Splines}.
#'@seealso \code{\link{foldsGenerator}}
#'
#'@export

multifoldCV<-function(cores=NULL,lambda,tau,sim.data,cv.idx){

  if(is.null(cores)) {cores=3}
  registerDoParallel(cores=cores)

  nfolds<-max(cv.idx)

  ## loop through, holding out one set of data at each point
  Fid<-foreach(i = 1:nfolds,.combine="c")%dopar%{
    hold.out.idx=which(cv.idx==i)
    keep.in.data<-sim.data[-hold.out.idx,]
    mod <- rqss(y ~ qss(x, lambda = lambda), tau = tau, data = keep.in.data)
    new.data<-sim.data[hold.out.idx,]
    extrapolated <- new.data$x > max(keep.in.data$x) | new.data$x < min(keep.in.data$x)

    y.pred<-as.vector(predict(mod,newdata=new.data[!extrapolated,]))
    mean(rho(tau=tau,x=new.data$y[!extrapolated]-y.pred))
  }
  return(mean(Fid))
}


#'\code{multifoldCV_2dim} calculates the same criterion for 2-dim covariate data sets.
#' @name multifoldCV_2dim
#' @rdname multifoldCV
#' @export


multifoldCV_2dim<-function(cores=NULL,lambda,tau,sim.data,cv.idx){
  library(quantreg)
  library(doParallel)
  library(foreach)
  library(tripack)
  if(is.null(cores)) {cores=3}
  registerDoParallel(cores=cores)

  nfolds<-max(cv.idx)

  ## loop through, holding out one set of data at each point
  Fid<-foreach(i = 1:nfolds,.combine="c")%dopar%{
    hold.out.idx=which(cv.idx==i)
    keep.in.data<-sim.data[-hold.out.idx,]
    mod <- rqss(y ~ qss(cbind(x1,x2), lambda = lambda, ndum=0), tau = tau, data = keep.in.data)
    new.data<-sim.data[hold.out.idx,]
    tri<-tripack::tri.mesh(mod$qss[[1]][[1]][,1], mod$qss[[1]][[1]][,2])
    NONextrapolated<-tripack::in.convex.hull(tri, new.data$x1, new.data$x2)


    y.pred<-as.vector(predict(mod, newdata = new.data[NONextrapolated,]))
    mean(rho(tau=tau,x=new.data$y[NONextrapolated]-y.pred))
  }
  return(mean(Fid))
}


#'\code{rho} is a function to plot the results.
#' @name rho
#' @rdname multifoldCV
#' @export

rho<-function(tau,x){
  return(x*(tau-I(x<0)))
}
